#!/usr/bin/env bash
#
# gitstat :: find git repos and print git status
# requires: bash 4.0+, git, find, sort

trap 'echo -e "\nSIGINT Received... exiting"; exit 130' SIGINT

# global variables
declare magenta="\033[0;35m"
declare reset="\033[0m"

err() {
  # send errors to standard error
  echo "$*" >&2
}

show_help() {
  # help option text
  echo "Usage: ${0##*/} [-d <top-level directory>] [-i <directory to ignore>]"
  echo "Options:"
  echo "  -h, --help    Show this help menu"
  echo "  -d <dir>      Specify the top level directory to search from"
  echo "  -i <dir>      Ignore a specific directory from results (repeatable)"
  echo "  -l            Only list git repos, and skip default action"
}

parse_options() {
  # parse arguments and assign variables, arrays

  # check for long "--help"
  if [[ "$1" == "--help" ]]; then
    show_help
    exit 0
  fi

  local opt
  while getopts ":hd:i:l" opt; do
    case "$opt" in
      h) show_help; exit 0 ;;
      d)
        top_dir="$OPTARG"
        if ! [[ -d "${top_dir}" ]]; then
          err "Directory not found: ${top_dir}"
          echo
          show_help
          exit 1
        fi
        ;;
      i)
        # strip trailing '/' from the argument if present
        local s
        s="${OPTARG%/}"
        if ! [[ "${s}" =~ ^(/|\.\.?/) ]]; then
          s="./${s}"
        fi
        excluded_dirs+=("${s}")
        ;;
      l) opt_list="1" ;;
      \?)
        err "Invalid option: -$OPTARG"
        show_help
        exit 1
        ;;
    esac
  done
}

fetch_git_repos() {
  # find all .git repositories under $1 path and place them into an array
  #
  # ARG $1: top-level directory
  # RET: git repositories

  local -a d_a
  readarray -t d_a < \
            <(find "$1" -type d -name ".git" -exec dirname {} \; 2>/dev/null \
                | sort)

  # return
  echo -n "${d_a[@]}"
}

validate_excluded_dirs() {
  # check excluded directories and remove if non-valid
  #
  # ARG $@: array of user specified excluded directories
  # RET: array of validated directories to exclude

  local -a d_a
  local d
  for d in "$@"; do
    if [[ -d "$d" ]]; then
      d_a+=("$d")
    elif ! [[ -d "$d" ]]; then
      err "Directory not found: $d ..."
    fi
  done

  # return
  echo -n "${d_a[@]}"
}

_remove_validated_excluded_dirs() {
  # removes directories named in $@ from $git_repos[]
  #
  # REQ: $checked_excluded_dirs[]
  # REQ: $git_repos[]

  local d
  # Iterate over git_repos
  for d in "${valid_excluded_dirs[@]}"; do
    # shellcheck disable=SC2206
    git_repos=(${git_repos[@]/${d}*})
  done
}

print_array() {
  # iterate through an array and print each element on a newline
  #
  # ARG $1: array

  local e
  for e in "$@"; do
    echo "$e"
  done
}

gitstat_run() {
  # iterate through found git repos and print their git status
  #
  # ARG $1: array of git repo directories

  local d
  for d in "$@"; do
    printf -- "--- "
    printf "${magenta}%s${reset}\n" "${d%%\/.git}"
    cd "${d}" || exit 1
    git status
    printf -- "---\n\n"
    cd - >/dev/null 2>&1 || exit 1
  done
}

main() {
  # parse options
  local opt_list top_dir
  local -a excluded_dirs git_repos valid_excluded_dirs
  parse_options "$@"

  # check for existance of $top_dir;
  # if it wasn't set by an argument, set it to pwd
  if [[ -z "$top_dir" ]]; then
    top_dir=.
  fi

  # fetch the git repositories and assign to git_repos
  read -r -a git_repos < <(fetch_git_repos "$top_dir")

  # validate excluded_dirs array, removing invalid arguments
  read -r -a valid_excluded_dirs < \
       <(validate_excluded_dirs "${excluded_dirs[@]}")

  # remove excluded directories from git_repos
  # git_repos - checked_excluded_dirs = git_repos
  _remove_validated_excluded_dirs

  # run list output if specified
  if [[ "$opt_list" -eq 1 ]]; then
    print_array "${git_repos[@]}"
    exit 0
  fi

  # run primary output
  gitstat_run "${git_repos[@]}"
}

main "$@"
